---
#
#
#


- name: Sync Local Files to S3 Bucket
  gather_facts: no
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:


  - name: Sync Local Files to Bucket {{ aws.s3.bucket_name }}
    community.aws.s3_sync:
      bucket: "{{ aws.s3.bucket_name }}"
      file_root: files   # local path to sync
    register: result

  # - ansible.builtin.debug: var=result


  - name: Get List of {{ aws.s3.bucket_name }} Bucket Keys
    amazon.aws.aws_s3:
      bucket: "{{ aws.s3.bucket_name }}"   # [a-zA-Z0-9-]
      mode: list
    register: result

  - name: List {{ aws.s3.bucket_name }} Bucket Keys
    ansible.builtin.debug: var=result.s3_keys


...