---
#------------------------------------------------------------------------------
# Ansible playbook to Create AWS S3 Static Web Site
#------------------------------------------------------------------------------

- name: Create AWS S3 Static Web Site
  hosts: localhost
  gather_facts: yes   # required for `ansible_date_time`
  vars_files: vars.yaml
  tasks:


  - name: Create an S3 bucket
    amazon.aws.s3_bucket:
      name: "{{ aws.s3.bucket_name }}"   # [a-zA-Z0-9-]
      state: present
      public_access:
        block_public_acls: no
        block_public_policy: no
        ignore_public_acls: no
        restrict_public_buckets: no
      versioning: no    # store multiple versions in case of accidents?
      tags:
        Name: "{{ aws.s3.bucket_name }}"
        product: "S3"
        project: "{{ project_name }}"
        start_date: "{{ ansible_date_time.date }}"
    register: result

  # - ansible.builtin.debug: var=result


  - name: Sync Local Files to Bucket {{ aws.s3.bucket_name }}
    community.aws.s3_sync:
      bucket: "{{ aws.s3.bucket_name }}"
      file_root: files   # local path to sync
      permission: public-read
    register: result

  # - ansible.builtin.debug: var=result


  - name: Get List of {{ aws.s3.bucket_name }} Bucket Keys
    amazon.aws.aws_s3:
      bucket: "{{ aws.s3.bucket_name }}"   # [a-zA-Z0-9-]
      mode: list
    register: result

  - name: List {{ aws.s3.bucket_name }} Bucket Contents
    ansible.builtin.debug: var=result.s3_keys


  # http://{{ aws.s3.bucket_name }}.s3-website-{{ aws.region }}.amazonaws.com/{{ filepath }}
  - name: Configure an s3 bucket as a website (HTTP)
    community.aws.s3_website:
      name: "{{ aws.s3.bucket_name }}"
      state: present
      suffix: index.html    # Default: "index.html"
      error_key: 404.html
    register: result

  # - ansible.builtin.debug: var=result


  - name: Access Your AWS S3 Bucket as a Static Web Site!
    ansible.builtin.debug: 
      msg: 
      - "http://{{ aws.s3.bucket_name }}.s3-website-{{ aws.region }}.amazonaws.com"


...