---


- name: Terminate Resources for Project "{{ project_name }}"
  hosts: localhost
  gather_facts: no
  vars_files: vars.yaml
  vars_prompt:
    - name: project_name
      prompt: Project Name
      default: "{{ project_name }}"
      private: no
  tasks:


  - name: Lists all {{ project_name | replace('_','-') }} S3 buckets
    community.aws.aws_s3_bucket_info:
      name_filter: "{{ project_name | replace('_','-') }}"
    register: result

  - ansible.builtin.debug: var=result['buckets']

  - name: Delete {{ project_name | replace('_','-') }} Buckets and All Contents
    loop: "{{ result['buckets'] }}"
    amazon.aws.aws_s3:
      bucket: "{{ item.name }}"   # [a-zA-Z0-9-]
      mode: delete


...